### ISSUE TITLE
Latest version not working

### ISSUE THREAD

**Issue by tajriba** [mollie/PrestaShop#1022]
Kan actie Upgrade niet toepassen op mollie. SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'id_method' used in key specification without a key length

Version 6.2.4 > 6.2.5

**Comment by stefanplk3** [comment]
Same problem with the download from your "updated" release!

![Image](https://github.com/user-attachments/assets/86829780-20b6-466b-8835-81d6a5aad5bb)

**Comment by justelis22** [comment]
Hi there @stefanplk3,

Please try to download the new version now, we uploaded some changes that should fix the issue.

If you have any questions, please let me know!

Best Regards,
Invertus Support team.

**Comment by stefanplk3** [comment]
Still the same error when upgrading to Version 6.2.6:

![Image](https://github.com/user-attachments/assets/1caf0a40-e243-4b8d-8775-1134594ff51a)

Installation des Moduls mollie fehlgeschlagen: SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'id_method' used in key specification without a key length

Please re-open the issue and please provide a fix.

**Comment by justelis22** [comment]
Hi there @stefanplk3,

We have checked this issue and tried to recreate it locally on our environments, however, everything seems to be working fine, but we were not able to prompt this issue.

That being said, we will need access to your shop to debug the issue. Can you provide the Back Office and FTP credentials?
If you have a development environment, that would be even better. That way, we can work on the issue without disturbing the live store.

You can add the credentials here - https://privatebin.net/ and share the link with us via email at support@invertus.eu.

Thanks!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
@stefanplk3,

pinging you again in case you missed my previous message.

Best Regards,
Invertus Support team.
